### ISSUE TITLE
Could the nodes be converted to structs?

### ISSUE THREAD

**Issue by kd7uiy** [BlueRaja/High-Speed-Priority-Queue-for-C-Sharp#19] opened 2017-01-15 02:32 UTC
It seems to me that the nodes are just data files. As such, it might be possible to use structs, which could use less memory and possibly be faster. My first blush look at it says it could work, but you have a better testing setup than I do.

Side node, thanks for this awesome library, it's the best PriorityQueue I've found for C#!

**Comment by BlueRaja** [comment] 2017-01-15 04:28
Duplicate of #3. tl;dr you can't keep `Contains(1)` to be O(1) with structs.

**Closed as completed by BlueRaja** 2017-01-15 04:28 UTC
