### ISSUE TITLE
File Not Found Exception in UWP projects

### ISSUE THREAD

**Issue by Nicolaasjvv** [BlueRaja/High-Speed-Priority-Queue-for-C-Sharp#20] opened 2017-01-18 12:02 UTC
When porting a Windows 8.1 Universal app to Windows 10 UWP, we suddenly started getting File not found exceptions for classes using the priority queue. I tested it in isolation, creating a new project, referencing the latest PriorityQueue library (4.0.0) obtained through NuGet, and we still get the same. 

Here are some details:

**When does this happen**
During run time, whenever a priority queue object is instanciated. Otherwize, the project builds just fine.

**What happens**

A file not found exception is thrown, here is the complete message:

`An exception of type 'System.IO.FileNotFoundException' occurred in TestApp.exe but was not handled in user code`

`Additional information: Could not load file or assembly 'Priority Queue UWP, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.`

**How is the code used.**

Just a simple initializer will do, see this sample:
[TestPage.txt](https://github.com/BlueRaja/High-Speed-Priority-Queue-for-C-Sharp/files/713793/TestPage.txt)

**Additional info**
For Windows 10 UWP, the following target platforms and minimum versions were specified during project creation.

![targetplatform](https://cloud.githubusercontent.com/assets/14290628/22063218/523fd40c-dd86-11e6-85b4-3aa0b1e37bb6.png)

 I cannot think of a reason for this to happen, all the files are safely where they should be, although with windows 10 projects, all NuGet packages are stored on disk under C:/{UserName}/.nuget/packages. All files are present.

**Comment by winterscar** [comment] 2017-02-27 12:11
I'm experiencing the same issue with the exact same configuration.

**Comment by BlueRaja** [comment] 2017-03-05 12:27
Looks like a versioning issue?  You say you're using the latest version (4.0.0) but that error says it's looking for version 3.0.0.  Try searching for `Priority Queue UWP, Version=3.0.0.0` in your project/solution files and see what turns up.

**Comment by BlueRaja** [comment] 2017-03-05 13:09
I've added support for both .Net Standard 1.0 and PCL `net40+sl5+win8+wpa81+wp8` in version 4.0.2.  If this was caused by the library not supporting the correct framework version, it should be fixed now.

Please reopen if you encounter this issue again.

**Closed as completed by BlueRaja** 2017-03-05 13:09 UTC
